### ISSUE TITLE
Version not available on npmjs

### ISSUE THREAD

**Issue by marcinant** [gomoob/grunt-phpdocumentor#4]
Version 0.3.0 is not available to download via npmjs.

Version 0.1.0 returns error:

```
File: [no files]
phpdoc --target= --directory=>> Exited with code: 1.

Error: Command failed: 


  [InvalidArgumentException]                
  Either an empty path or root was given:   



project:run [-t|--target[="..."]] [-f|--filename[="..."]] [-d|--directory[=".
.."]] [--encoding[="..."]] [-e|--extensions[="..."]] [-i|--ignore[="..."]] [-
-ignore-tags[="..."]] [--hidden] [--ignore-symlinks] [-m|--markers[="..."]] [
--title[="..."]] [--force] [--validate] [--visibility[="..."]] [--defaultpack
agename[="..."]] [--sourcecode] [-p|--progressbar] [--template[="..."]] [--pa
rseprivate] [-c|--config[="..."]]                                           



Initializing parser and collecting files .. 



  [InvalidArgumentException]                
  Either an empty path or root was given:   



project:run [-t|--target[="..."]] [-f|--filename[="..."]] [-d|--directory[=".
.."]] [--encoding[="..."]] [-e|--extensions[="..."]] [-i|--ignore[="..."]] [-
-ignore-tags[="..."]] [--hidden] [--ignore-symlinks] [-m|--markers[="..."]] [
--title[="..."]] [--force] [--validate] [--visibility[="..."]] [--defaultpack
agename[="..."]] [--sourcecode] [-p|--progressbar] [--template[="..."]] [--pa
rseprivate] [-c|--config[="..."]]                                           

```

**Comment by mitermayer** [comment]
- 1 please add version 0.3.0 to npm

**Comment by bgaillard** [comment]
Hi, the version 0.3.0 is published on npm. 

So sorry for the delay !

@marcinant I was using the version 0.1.0 until now and tried to switch one of our project to version 0.3.0 but it seems their is a bug under Windows. If you are also using Windows I'm planning to release a 0.3.1 which will fix it.

**Comment by marcinant** [comment]
I'm not using Windows. Sorry. But thank you anyway.

**Comment by bgaillard** [comment]
Hi again, I've create a new 0.4.0 release of the plugin.

If you have the time could you test it and indicate if it works now ? 

If not can you provide me the following informations :  
- The operating system your are using
- Your PHP version

Now the plugin unit tests are run on our Jenkins continuous integration server, I hope it will help to prevent regressions and fix UNIX bugs.

Thanks for your help, 

Baptiste

**Comment by marcinant** [comment]
Sure. But I'll have time for this tomorrow.
