### ISSUE TITLE
Tag and publish 0.3.0 to npm registry

### ISSUE THREAD

**Issue by paazmaya** [gomoob/grunt-phpdocumentor#5]
Create a tag 'v0.3.0' and publish it to npm registry.

**Comment by mitermayer** [comment]
+1 please add 0.3.0 to npm

**Comment by bgaillard** [comment]
Version 0.3.0 is now published on npm. 

If you are using Windows I think their is a blocking bug, I'm planning to release a 0.3.1 soon to fix it.
